# Generated by Django 3.1.7 on 2021-03-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0006_auto_20210326_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=1),
        ),
    ]
